# Generated by Django 4.2.6 on 2023-11-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='ano',
            field=models.CharField(max_length=200, null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=200, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='paginas',
            field=models.CharField(max_length=200, null=True, verbose_name='Número de Páginas'),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='editora',
            field=models.CharField(max_length=200, verbose_name='Editora'),
        ),
    ]
